#PBS -N qm_xiepai_ahl_plain_6_1_val_threshold_20260518_S8
#PBS -q batch
#PBS -o /ghome/huangjd/code/detected/adpretrain_bridge/pbs/ahl_adp_plain_mqs.out
#PBS -e /ghome/huangjd/code/detected/adpretrain_bridge/pbs/ahl_adp_plain_mqs.err
#PBS -l nodes=1:gpus=1:A
#PBS -r y
#PBS -m abef

SCRIPT_FILE_PATH=/ghome/huangjd/code/detected/adpretrain_bridge/pbs/generated_run/run_qm_xiepai_ahl_plain_6_1_val_threshold_20260518_S8.sh
IMAGE_NAME=bit:5000/deepo

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
echo -n "Node:"
cat $PBS_NODEFILE
echo -n "Gpus:"
cat $PBS_GPUFILE
echo "CUDA_VISIBLE_DEVICES:"$CUDA_VISIBLE_DEVICES

chmod +x $SCRIPT_FILE_PATH
startdocker -P /ghome/huangjd -D /gdata1 \
-u "--ipc=host --shm-size 192G -e HOME=/ghome/huangjd" \
-s $SCRIPT_FILE_PATH \
$IMAGE_NAME


